name: GX Validation

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/gx_run.yaml'
      - '**'

permissions:
  contents: write

jobs:
  gx-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Write GCP credentials to file
        run: |
          echo "$GOOGLE_CREDENTIALS" > gcp_key.json
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Build Docker image
        run: |
          docker build -t salary-survey-gx .

      - name: Run GX Validation in Docker and output docs
        run: |
          mkdir -p gx_docs_output
          docker run --rm \
            -e GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcp_key.json \
            -v ${{ github.workspace }}/gcp_key.json:/tmp/gcp_key.json \
            -v ${{ github.workspace }}/gx_docs_output:/app/great_expectations/gx_docs_output \
            salary-survey-gx

      - name: Push GX docs to gh-pages branch
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          # Clone the gh-pages branch into a separate folder
          git fetch origin gh-pages
          git switch --force-create gh-pages origin/gh-pages

          mkdir -p gx_site
          cp -r gx_docs_output/. gx_site/

          git add gx_site
          git commit -m "Update GX docs [auto]" || echo "No changes to commit"
          git push origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
