name: GX Validation

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/gx_validation.yaml'
      - 'salary_survey_gx/**'

jobs:
  gx-run:
    runs-on: ubuntu-latest
    environment: prod

    env:
      GCP_PROJECT_ID: ${{ vars.PROJECT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Docker Registry (optional if pushing image)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GCP keyfile for Docker
        run: echo "${{ secrets.GOOGLE_CREDENTIALS }}" > ./gcp_key.json

      - name: Build Docker image
        run: |
          docker build -t salary-survey-gx ./salary_survey_gx

      - name: Run GX Validation in Docker
        run: |
          docker run --rm \
            -e GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcp_key.json \
            -v ${{ github.workspace }}/gcp_key.json:/tmp/gcp_key.json \
            salary-survey-gx
